blog/urls.py
from django.urls import path

from .views import (
    BlogListView, BlogDetailView, UpdateCreateView, BlogCreateView, BlogUpdateView, BlogDeleteView,
)

urlpatterns = [
    path('update/new/', UpdateCreateView.as_view(), name='update_new'),
    path('post/<int:pk>/delete/',
         BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/',
         BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('', BlogListView.as_view(), name='home'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Post(models.Model):
    REQUIREMENT_TYPES = (
        ('N', "New Requirement"),
        ('E', "Enhancement"),
        ('R', "Roll Out"),
        ('T', "Training"),
    )
    PRIORITASS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    TARGETS = (
        ('1', 'TW-I'),
        ('2', 'TW-II'),
        ('3', 'TW-III'),
        ('4', 'TW-IV'),
    )
    DIR_APS = (
        ('CON', 'Controller'),
        ('DEV', 'Development'),
        ('FIN', 'Finance & Treasury'),
        ('HR', 'HR-GA'),
        ('ICT', 'ICT & DM'),
        ('AUDIT', 'Internal Audit'),
        ('LEGAL', 'Legal'),
        ('NUN', 'Nunukan'),
        ('ONWJ', "ONWJ"),
        ('OPS', 'Operation & Production'),
        ('PHI', 'PHI'),
        ('PPRM', 'PPRM'),
        ('QHSSE', 'QHSSE'),
        ('REL', 'Relation'),
        ('SCM', 'SCM'),
        ('SK', 'Siak-Kampar'),
        ('CO', 'Commercial'),
        ('WMO', 'WMO'),
    )
    user1 = models.CharField(max_length=15)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    dir_ap = models.CharField(max_length=5, choices=DIR_APS)
    requirement = models.TextField()
    requirement_type = models.CharField(max_length=1, choices=REQUIREMENT_TYPES)
    prioritas = models.CharField(max_length=1, choices=PRIORITASS)
    target = models.CharField(max_length=1, choices=TARGETS)
    budget = models.IntegerField()

    def __str__(self):
        return self.requirement[:50]

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Update(models.Model):
    STATUSS = (
        ('C', 'Closed'),
        ('D', 'Dropped'),
        ('E', 'Execution'),
        ('I', 'Initiation'),
        ('P', 'Planning'),
    )
    posting = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='updates',)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    last_update = models.DateField(auto_now_add=False)
    progress = models.IntegerField()
    status = models.CharField(max_length=1, choices=STATUSS)
    status_akhir = models.TextField()

    def __str__(self):
        return self.status_akhir[:50]


    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.posting.id)])

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
from .models import Post, Update


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'all_posts_list'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


class UpdateListView(ListView):
    model = Update
    template_name = 'update.html'
    context_object_name = 'all_updates_list'


class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = ['requirement', 'user1', 'author', 'dir_ap', 'requirement_type', 'prioritas', 'target', 'budget']


class UpdateCreateView(CreateView):
    model = Update
    template_name = 'update_new.html'
    fields = ['posting', 'author', 'last_update', 'progress', 'status', 'status_akhir']


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['requirement', 'user1', 'author', 'dir_ap', 'requirement_type', 'prioritas', 'target', 'budget']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BD Mon</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
    rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <div class="nav-left">
            <h1>
                <a href="{% url 'home' %}">BD Mon</a>
            </h1>
        </div>
        <div class="nav-right">
            <a href="{% url 'post_new' %}">+ New Req</a>
        </div>
    </header>

    {% if user.is_authenticated %}
        <p>Hallo {{ user.username }}!</p>
        <p><a href="{% url 'logout' %}">Log out</a></p>

    {% else %}
        <p>Anda belum login.</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}


    <div>
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% for post in all_posts_list %}
        <div class="post-entry">
            <h2><a href="{% url 'post_detail' post.pk %}">Requirement: {{  post.requirement }}  </a></h2>
            <p>User name:  {{ post.user1   }}</p>
            <p>Director/AP:  {{ post.get_dir_ap_display }}</p>
        </div>
    {% endfor %}
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
        <h1>Delete Req:</h1>
        <form action="" method="post">{% csrf_token %}
            <p>Betulkan mau delete "{{ object.requirement }}"?</p>
            <input type="submit" value="Confirm" />
        </form>

{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

        <div class="post-entry">
            <h2><a href="">Requirement: {{  object.requirement }}  </a></h2>
            <p>User name:  {{ object.user1   }}</p>
            <p>Author: {{ object.author   }}</p>
            <p>Director/AP:{{ object.get_dir_ap_display }}</p>
            <p>Req. Type: {{ object.get_requirement_type_display   }}</p>
            <p>Prioritas: {{ object.get_prioritas_display   }}</p>
            <p>Target: {{ object.get_target_display   }}</p>
            <p>Budget: kIDR {{ object.budget   }}</p>
        </div>

        <p><a href="{% url 'post_edit' post.pk %}">+ Edit Req</a></p>
        <p><a href="{% url 'post_delete' post.pk %}">+ Delete Req</a></p>

        <div class="post-entry">
            <a href="{% url 'update_new' %}">+ New Status</a>
            <h2><a href="">Status: </a></h2>
            {% for comment in post.updates.all %}
                <p>Oleh: {{ comment.author }}</p>
                <p>Tanggal: {{ comment.last_update }} </p>
                <p>Progres: {{ comment.progress }} % </p>
                <p>Status:  {{ comment.get_status_display }}</p>
                <p>Status Akhir: {{ comment.status_akhir }}</p>
                <p>------------------------------------------------------------------------------------------------</p>
            {% endfor %}

        </div>

{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Requirement edit:</h1>
    <form action ="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>Requirement baru:</h1>
    <form action ="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock content %}

templates/update_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update status:</h1>
    <form action ="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock content %}